# Generated by Django 4.2.4 on 2023-08-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_token',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ключ верификации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активный'),
        ),
    ]
