# Generated by Django 4.2.4 on 2023-08-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=10, verbose_name='версия')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'версия продукта',
                'verbose_name_plural': 'версии продукта',
            },
        ),
    ]
